### ISSUE TITLE
Support dotAll flag

### ISSUE THREAD

**Issue by monkeyWie** [dlclark/regexp2#83]
Thank you for this great project, but it seems that the `dotAll` option is not supported now, is there any way to achieve it?

**Comment by dlclark** [comment]
My understanding is that dotAll is a synonym for “regexp2.Singleline” option or (?s)

**Comment by monkeyWie** [comment]
Ya, but

**Comment by monkeyWie** [comment]
Using `regexp2.Singleline` alone is fine.

**Comment by dlclark** [comment]
What exactly doesn't work?  I'll need a regex, options, match text, and what you expected the match to be. I suggest the form of a unit test.

**Comment by monkeyWie** [comment]
Thanks for the quick reply, below is the unit test code:

```
// It works fine
func TestRegexpSingleline(t *testing.T) {
	re := regexp2.MustCompile(`.`, regexp2.Singleline)
	if isMatch, _ := re.MatchString("\n"); !isMatch {
		t.Fatal("Expected match")
	}
}
```

```
// It not work
func TestRegexpECMAScriptWithSingleline(t *testing.T) {
	re := regexp2.MustCompile(`.`, regexp2.ECMAScript | regexp2.Singleline)
	if isMatch, _ := re.MatchString("\n"); !isMatch {
		t.Fatal("Expected match")
	}
}
```

![image](https://github.com/user-attachments/assets/bee7d686-5e29-4fc1-ba58-b1bba365fc2b)

**Comment by dlclark** [comment]
This is now fixed -- the regex parser's if/elseif block was backwards for dot. Singleline should always include all chars and EcmaScript only has a different set for dot if Singleline isn't set.

Thanks for the report!

**Comment by monkeyWie** [comment]
I just upgraded to the latest version but still have problems. It seems that the latest submit only added a unit test

**Comment by dlclark** [comment]
Well that's embarrassing. My `git add *.go` missed that the change was in the `syntax` folder. Code now shipped.

**Comment by monkeyWie** [comment]
Thanks, it work well now!
